

/* TODO: Replace [dbo].[MyTableName] with the name of your specific table */


-- step 1: Create hypothetical indexes using the WITH STATISTICS_ONLY clause:

/* TODO: Replace with your own index definitions, but don't forget to use WITH STATISTICS_ONLY */

CREATE NONCLUSTERED INDEX [IX_Hypothetical_1]
ON [dbo].[MyTableName] ( [column1], [column2] )
WITH STATISTICS_ONLY
GO
CREATE NONCLUSTERED INDEX IX_Hypothetical_2
ON [dbo].[MyTableName] ( [column2], [column3])
WITH STATISTICS_ONLY
GO

-- step 2: Generate DBCC AUTOPILOT commands to mark hypothetical indexes for AUTOPILOT:

-- DBCC AUTOPILOT (TYPE_ID,DB_ID,OBJECT_ID,INDEX_ID);
SELECT CONCAT(N'DBCC AUTOPILOT(0,', DB_ID(), N',', object_id, N',', index_id, N');'), name
FROM sys.indexes
WHERE object_id = OBJECT_ID('[dbo].[MyTableName]')
AND is_hypothetical = 1
GO
-- step 3: copy-paste and run the DBCC AUTOPILOT commands generated above

/* TODO: paste here DBCC AUTOPILOT commands */

GO
-- step 4: run the below to generate an estimated plan assuming the existence of hypothetical indexes marked for autopilot
GO
SET AUTOPILOT ON;
GO
/* TODO: Add your test query here */
GO
SET AUTOPILOT OFF;
GO

-- step 5: you may drop your hypothetical indexes now using command(s) generated by running below:

SELECT N'DROP INDEX ' + QUOTENAME(name) + N' ON ' + QUOTENAME(OBJECT_SCHEMA_NAME(object_id)) + N'.' + QUOTENAME(OBJECT_NAME(object_id)) + N';'
FROM sys.indexes
WHERE object_id = OBJECT_ID('[dbo].[MyTableName]')
AND is_hypothetical = 1
GO
